# -*- coding: utf-8 -*-
"""sw영재원 sw프로젝트(서수안)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQ0fqcKg_YstHVaME8ACh7pjOCCCI5rO
"""

import os
print(os.listdir("/content"))

import zipfile

zip_path = "/content/GARBAGE CLASSIFICATION.zip"

print(zipfile.is_zipfile(zip_path))

import zipfile

zip_path = "/content/GARBAGE CLASSIFICATION.zip"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall("/content")

print("unzip clear")

import os

print(os.listdir("/content/GARBAGE CLASSIFICATION"))

import os

base = "/content/GARBAGE CLASSIFICATION"

print("train images:", len(os.listdir(f"{base}/train/images")))
print("train labels:", len(os.listdir(f"{base}/train/labels")))

print("valid images:", len(os.listdir(f"{base}/valid/images")))
print("valid labels:", len(os.listdir(f"{base}/valid/labels")))

print("test images:", len(os.listdir(f"{base}/test/images")))
print("test labels:", len(os.listdir(f"{base}/test/labels")))

!pip install -q ultralytics

from ultralytics import YOLO

print("YOLO ready")

yaml_path = "/content/GARBAGE CLASSIFICATION/data.yaml"

with open(yaml_path, "r") as f:
    print(f.read())

from ultralytics import YOLO

model = YOLO("yolo26n.pt")

print("✅ YOLO 모델 준비 완료!")

results = model.train(
    data="/content/GARBAGE CLASSIFICATION/data.yaml",
    epochs=1,
    imgsz=416,
    batch=8,
    project="/content/runs",
    name="garbage_detector"
)